version: '3.7'

services:
  redis:
      image: redis:alpine
      command: redis-server --requirepass ${REDIS_PASSWORD}
      ports:
        - ${REDIS_PORT}:6379
      restart: always
      networks:
        - app-network

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "${APP_PORT}:5000"
    environment:
      API_KEY: ${API_KEY}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: on-failure
    depends_on:
      - redis
    networks:
      - app-network


networks:
  app-network: